server {
  listen 80;
  root /usr/share/nginx/html;

  location / {
    try_files $uri /index.html;
  }

  location /chat {
    proxy_pass http://backend:8080;
  }
  
  location /chatHub { # Or your specific WebSocket path
      proxy_pass http://backend:8080; # Your backend server address
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host; # Optional, but good practice
  }

}
