server {
  listen 80;
  server_name gustavoqueiroz.dev www.gustavoqueiroz.dev;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name gustavoqueiroz.dev www.gustavoqueiroz.dev;

  ssl_certificate     /etc/letsencrypt/live/gustavoqueiroz.dev/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/gustavoqueiroz.dev/privkey.pem;

  location / {
    try_files $uri /index.html;
  }

  location /chat {
    proxy_pass http://backend:8080;
  }

  location /chatHub {
    proxy_pass http://backend:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }

  location /.well-known/acme-challenge/ {
    root /usr/share/nginx/html;
  }
}
