services:
  backend:
    image: guessst/chat-backend:latest
    build:
      context: .
  
  frontend:
    image: guessst/chat-frontend:latest
    build:
      context: .
    ports:
      - "443:443"
    volumes:
      - /var/www/certbot:/usr/share/nginx/html/.well-known/acme-challenge
      - ./frontend/nginx.production.conf:/etc/nginx/conf.d/default.conf:ro

